[package]
name = "rosist-sallina-tg-rcore-tutorial-T3L3"
description = "Student AI4OSE extension lab crate for Chapter 3 of rCore Tutorial: framebuffer snake with polling and IRQ input."
edition = "2024"
version = "0.0.1-preview.1"
authors = ["Rosist_Sallina <sallinarosist@gmail.com>"]
repository = "https://github.com/Rosist-Sallina/tg-rcore-tutorial"
homepage = "https://github.com/Rosist-Sallina/tg-rcore-tutorial/tree/test/tg-rcore-tutorial-ch3"
documentation = "https://docs.rs/rosist-sallina-tg-rcore-tutorial-T3L3"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["no-std", "embedded"]
exclude = [
    "tg-user/**",
#    ".cargo/config.toml",
]

[features]
coop = []
exercise = []
snake = []
irq_input = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
virtio-drivers = { package = "rosist-sallina-tg-rcore-tutorial-virtio-drivers-t3l3", path = "../vendor/virtio-drivers", version = "0.0.1-preview.1" }
riscv = "0.10.1"
spin = "0.9"

tg-sbi = { package = "tg-rcore-tutorial-sbi", path = "../tg-rcore-tutorial-sbi", version = "0.4.8", features = ["nobios"] }
tg-linker = { package = "tg-rcore-tutorial-linker", path = "../tg-rcore-tutorial-linker", version = "0.4.8" }
tg-console = { package = "tg-rcore-tutorial-console", path = "../tg-rcore-tutorial-console", version = "0.4.8" }
tg-kernel-context = { package = "tg-rcore-tutorial-kernel-context", path = "../tg-rcore-tutorial-kernel-context", version = "0.4.8" }
tg-kernel-alloc = { package = "tg-rcore-tutorial-kernel-alloc", path = "../tg-rcore-tutorial-kernel-alloc", version = "0.4.8" }
tg-syscall = { package = "rosist-sallina-tg-rcore-tutorial-syscall-t3l3", path = "../tg-rcore-tutorial-syscall", version = "0.0.1-preview.1", features = ["kernel"] }

[build-dependencies]
tg-linker = { package = "tg-rcore-tutorial-linker", path = "../tg-rcore-tutorial-linker", version = "0.4.8" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
