[package]
name = "tg-rcore-tutorial-smp"
description = "Basic SMP support helpers for the rCore tutorial labs."
version = "0.4.8"
edition = "2024"
authors = ["Rosist_Sallina <sallinarosist@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
keywords = ["rcore", "smp", "riscv"]
categories = ["no-std", "embedded", "concurrency"]

[dependencies]
riscv = "0.10.1"

