[package]
name = "rosist-sallina-tg-rcore-tutorial-user-t1l5"
description = "Student AI4OSE lab user-space apps crate for Chapter 8 of rCore Tutorial."
version = "0.0.1-preview.1"
edition = "2024"
authors = ["Rosist_Sallina <sallinarosist@gmail.com>"]
repository = "https://github.com/Rosist-Sallina/tg-rcore-tutorial"
homepage = "https://github.com/Rosist-Sallina/tg-rcore-tutorial/tree/test/tg-rcore-tutorial-user"
documentation = "https://docs.rs/rosist-sallina-tg-rcore-tutorial-user-t1l5"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["no-std", "embedded"]

[lib]
name = "user_lib"
path = "src/lib.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
tg-console = { package = "tg-rcore-tutorial-console", path = "../tg-rcore-tutorial-console", version = "0.4.2-preview.7" }
tg-syscall = { package = "rosist-sallina-tg-rcore-tutorial-syscall-t3l3", path = "../tg-rcore-tutorial-syscall", version = "0.0.1-preview.4", features = ["user"] }
customizable-buddy = "0.0.2"
